### ISSUE TITLE
[BUG] Edge update is getting beta version

### ISSUE THREAD

**Issue by chrissabato** [Svinokur/selenium_driver_updater#1]
**Describe the bug**
The current version is getting the Beta Channel version of Microsoft Edge Driver instead of the stable Channel version. It also appears to ignore  check_driver_is_up_to_date=True.

The following results in downloading edge driver version 96.0.1054.8, when the edge version is 95.0.1020.40  
DriverUpdater.install(im=True, path=base_dir, driver_name=DriverUpdater.edgedriver, upgrade=True, check_driver_is_up_to_date=True, check_browser_is_up_to_date=True)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Driver: edgedriver
 - Version: 5.1.2

**Additional context**

**Comment by Svinokur** [comment]
Hello, chrissabato, thanks for the bug. I fixed it in version 5.1.3, could you check that this bug is fixed for you?
