### ISSUE TITLE
[BUG] Not updating after Chrome version 114

### ISSUE THREAD

**Issue by GreatNewHope** [Svinokur/selenium_driver_updater#3]
**Describe the bug**
Chromedriver is not getting updated after version 114

**Additional context**
This stackoverflow issue describes it well https://stackoverflow.com/questions/76932496/webdrivermanager-setup-failing-to-download-chromedriver-116

Sorry for not adding more information...

**Comment by Svinokur** [comment]
Thanks for pointing out this issue. I have fixed it in a new released version 6.0.0
